service: serverless-glue-import-job
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        - arn:aws:s3:::easyb2b-iga/*
    - Effect: Allow
      Action:
        - glue:CreateTrigger
        - glue:CreateJob
        - glue:StartJobRun
      Resource: "*"

functions:
  trigger:
    handler: handler.trigger
    events:
      - s3:
          bucket: easyb2b-iga
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/via-varejo-imports
            - suffix: .xml
          existing: true

custom:
  pythonRequirements:
    pythonBin: python3
    zip: true

plugins:
  - serverless-python-requirements
  - serverless-glue

Glue:
  bucketDeploy: serverless-glue-import-job-bucket
  createBucket: true
  createBucketConfig:
    ACL: private
    LocationConstraint: us-east-2
  jobs:
    - name: serverless-glue-import-job
      scriptPath: glue.py
      Description: Glue Import Job
      tempDir: false
      type: spark
      glueVersion: python3-4.0
      role: arn:aws:iam::723297943207:role/GlueAccess
      MaxCapacity: 2
